<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-gustavoreiis/blob/main/Pr%C3%A1tica_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).
**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


In [1]:
import numpy as np

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [12]:
a = np.zeros(10)
a.dtype


dtype('float64')

In [13]:
a.shape

(10,)

### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.


In [18]:
b = np.ones(10)
res = np.float64(b)
res

dtype('float64')

### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [19]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [23]:
d = np.arange(9).reshape(3, 3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [29]:
v = np.array([1,2,0,0,4,0])
np.nonzero(v)
# Exibe o índice dos valores não nulos

(array([0, 1, 4]),)

### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [31]:
e = np.linspace(0, 1, 12)
e

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [33]:
f = np.eye(5)
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [39]:
rng = np.random.default_rng(42)
g = rng.random((3, 3, 3))
g

array([[[0.77395605, 0.43887844, 0.85859792],
        [0.69736803, 0.09417735, 0.97562235],
        [0.7611397 , 0.78606431, 0.12811363]],

       [[0.45038594, 0.37079802, 0.92676499],
        [0.64386512, 0.82276161, 0.4434142 ],
        [0.22723872, 0.55458479, 0.06381726]],

       [[0.82763117, 0.6316644 , 0.75808774],
        [0.35452597, 0.97069802, 0.89312112],
        [0.7783835 , 0.19463871, 0.466721  ]]])

### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.