<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-gustavoreiis/blob/main/Pr%C3%A1tica_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).
**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


In [6]:
import numpy as np

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [7]:
a = np.zeros(10)
a.dtype


dtype('float64')

In [8]:
a.shape

(10,)

### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.


In [9]:
b = np.ones(10)
res = np.float64(b)
res

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [10]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [11]:
d = np.arange(9).reshape(3, 3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [12]:
v = np.array([1,2,0,0,4,0])
np.nonzero(v)
# Exibe o índice dos valores não nulos

(array([0, 1, 4]),)

### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [13]:
e = np.linspace(0, 1, 12)
e

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [14]:
f = np.eye(5)
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [15]:
rng = np.random.default_rng(42)
g = rng.random((3, 3, 3))
g

array([[[0.77395605, 0.43887844, 0.85859792],
        [0.69736803, 0.09417735, 0.97562235],
        [0.7611397 , 0.78606431, 0.12811363]],

       [[0.45038594, 0.37079802, 0.92676499],
        [0.64386512, 0.82276161, 0.4434142 ],
        [0.22723872, 0.55458479, 0.06381726]],

       [[0.82763117, 0.6316644 , 0.75808774],
        [0.35452597, 0.97069802, 0.89312112],
        [0.7783835 , 0.19463871, 0.466721  ]]])

### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [16]:

h = rng.random((10, 10))
print("Mínimo: ", h.min())
print("Máximo: ", h.max())

Mínimo:  0.007362269751005512
Máximo:  0.9691763773477239


### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [17]:
i = [1, 2, 3, 4, 5]
i = np.array(i, dtype=float)
i_std = (i - i.mean()) / i.std()
print(i_std, i_std.mean(), i_std.std())

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356] 0.0 0.9999999999999999


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [21]:
j = np.array([1, 2, 3], dtype=np.int32)
jFloat = j.astype(np.float32)
jInt = jFloat.astype(np.int64)
print(j.dtype, jFloat, jInt)

int32 [1. 2. 3.] [1 2 3]


### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [25]:
k = np.array([2, 5, 7, 1, 9])
clipped = np.clip(k, 0, 5)
clipped

array([2, 5, 5, 1, 5])

### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).

In [26]:
l = np.arange(10)
li = np.flip(l)
li

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h = np.hstack((a, b))
v = np.vstack((a, b))
print(h)
print(v)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

In [28]:
m = np.diag(np.full(4, 5))
print(m)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [29]:
n = np.arange(12).reshape(3, 4)
soma_linhas = n.sum(axis=1)
soma_colunas = n.sum(axis=0)
print("linhas:", soma_linhas)
print("colunas:", soma_colunas)

linhas: [ 6 22 38]
colunas: [12 15 18 21]


### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

In [30]:
o = rng.integers(0, 10, size=100)
freq = np.bincount(o, minlength=10)
print(freq)

[ 7 13 13  9 11 13 10  5  6 13]


### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [31]:
p = np.arange(20)
x = p[1::3]
print(x)

[ 1  4  7 10 13 16 19]


### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

In [32]:
q = np.arange(20)
mask = (q % 2 == 0)
pares = q[mask]
print(mask)
print(pares)

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 0  2  4  6  8 10 12 14 16 18]


### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

In [33]:
r = [[1, 2, 3], [4, 5, 6]]
arr = np.array(r)
print(arr)
print("shape:", arr.shape, "dtype:", arr.dtype)


[[1 2 3]
 [4 5 6]]
shape: (2, 3) dtype: int64


### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).

In [34]:
datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(datas)

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

In [35]:
s = np.array([[1., 2., 3.],
              [4., 5., 6.]])
sCentered = s - s.mean(axis=0, keepdims=True)
print(sCentered)

[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

elem = a * b
dot1 = np.dot(a, b)
dot2 = a @ b
print(elem, dot1, dot2)

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

elem = a * b
dot1 = np.dot(a, b)
dot2 = a @ b
print(elem, dot1, dot2)

[ 4 10 18] 32 32


### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

In [37]:
A = np.arange(12).reshape(3, 4)
tmp = A[:, 0].copy()
A[:, 0] = A[:, 2]
A[:, 2] = tmp
print(A)

[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
c = a.ravel()

c[0] = 99

print(a)
print(b)

[[99  2  3]
 [ 4  5  6]]
[1 2 3 4 5 6]


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [45]:
d = np.zeros((8, 8), dtype=int);

d[1::2, ::2] = 1
d[::2, 1::2] = 1

d

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [46]:
x = np.arange(-5, 6)
y = np.where(x < 0, 0, x)
print("x:", x)
print("y:", y)

x: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
y: [0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [47]:
e = rng.random(1_000_000)
media = e.mean()
err_abs = abs(media - 0.5)
print("média:", media, "erro absoluto:", err_abs)

média: 0.5000343638694618 erro absoluto: 3.4363869461762064e-05


### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [48]:
a = np.array([1, 2, 3])[:, None]
b = np.array([10, 20, 30, 40])[None, :]
S = a + b
print(S)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [49]:
s = np.array([1, 2, 3, 4, 5])
k = np.array([2, 1])

k = np.flip(k)
jan = np.lib.stride_tricks.sliding_window_view(s, len(k))
conv = np.sum(jan * k, axis=1)

print(conv)

[ 5  8 11 14]
