<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-gustavoreiis/blob/main/Pr%C3%A1tica_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).
**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


In [1]:
import numpy as np

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [12]:
a = np.zeros(10)
a.dtype


dtype('float64')

In [13]:
a.shape

(10,)

### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.


In [18]:
b = np.ones(10)
res = np.float64(b)
res

dtype('float64')

### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [19]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [23]:
d = np.arange(9).reshape(3, 3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [24]:
v = np.array([1,2,0,0,4,0])
np.nonzero(v)

(array([0, 1, 4]),)